global:
  scrape_interval: 15s # Cu 15 giay se di lay du lieu 1 lan

scrape_configs:
  - job_name: 'openresty-metrics'
    metrics_path: '/metrics'
    static_configs:
      # Host-native OpenResty; container host.docker.internal qua host-gateway
      - targets: ['host.docker.internal:9145']
