server {
    listen 80 default_server;
    server_name _;

    root /usr/local/openresty/nginx/html;
    index index.html;

    include /usr/local/openresty/nginx/conf/includes/security/security-headers.conf;
    include /usr/local/openresty/nginx/conf/includes/security/global_block_list.conf;
    include /usr/local/openresty/nginx/conf/includes/security/waf.conf;

    location / {
        include /usr/local/openresty/nginx/conf/includes/security/rate_limit_location.conf;
        try_files $uri $uri/ =404;
    }
}
