server {
    listen 8888;  # Chi mo tren localhost
    allow 127.0.0.1;
    allow ::1;
    deny all;
    
    location /nginx_api/unban {
        content_by_lua_block {
            if ngx.req.get_method() ~= "POST" then
                ngx.status = ngx.HTTP_NOT_ALLOWED
                ngx.say("Chi chap nhan POST")
                return
            end
            local ip = ngx.req.get_uri_args()["ip"]
            local blacklist = ngx.shared.ip_blacklist

            if not ip then
            ngx.say("Thieu tham so ?ip=")
            return
            end

            -- Xoa IP khoi RAM
            blacklist:delete(ip)

            -- Xoa luon diem phat tich luy neu co
            if ngx.shared.violation_tracker then
            ngx.shared.violation_tracker:delete(ip)
            end

            ngx.say("Da unban thanh cong IP: " .. ip)
        }
    }

    # Endpoint xoa sach toan bo blacklist
    location /nginx_api/flush-all {
        content_by_lua_block {
            if ngx.req.get_method() ~= "POST" then
                ngx.status = ngx.HTTP_NOT_ALLOWED
                ngx.say("Chi chap nhan POST")
                return
            end
            ngx.shared.ip_blacklist:flush_all()
            ngx.say("Da xoa toan bo blacklist trong RAM!")
        }
    }
}
