add_header X-Frame-Options "DENY" always;
add_header X-Content-Type-Options "nosniff" always;
include /usr/local/openresty/nginx/conf/includes/security/basic-referrer-policy.conf;
include /usr/local/openresty/nginx/conf/includes/security/basic-cross-origin-resource-policy.conf;
include /usr/local/openresty/nginx/conf/includes/security/strict-transport-security.conf;

